name = "suanoo"
main = "src/index.js"
compatibility_date = "2023-01-25"
route = "suanoo.kali-team.cn/*"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[vars]
MY_DOMAIN = "suanoo.kali-team.cn"
NOTION_DOMAIN = "buttoned-ellipse-ba9.notion.site"
INDEX_PAGE_ID = "0bed722520de4a01879fde5443c8ef15"
LINK_PAGE_ID = "9c74faba0b14441a93c2f94a40da3f79"
PAGE_TITLE = "suanoo"
PAGE_DESCRIPTION = "suanoo"
SITEMAP_BODY = '{"source":{"type":"collection","id":"52de4e5e-ba6e-46a2-9dc5-5581637cf339","spaceId":"d4aa424b-d5f8-4dc3-a0fb-e5270f17203e"},"collectionView":{"id":"a5b688dd-2876-4f80-a47d-d84e713ac56e","spaceId":"d4aa424b-d5f8-4dc3-a0fb-e5270f17203e"},"loader":{"type":"reducer","reducers":{"collection_group_results":{"type":"results","limit":50},"table:uncategorized:title:unique":{"type":"aggregation","aggregation":{"property":"title","aggregator":"unique"}},"table:uncategorized:|oXv:latest_date":{"type":"aggregation","aggregation":{"property":"|oXv","aggregator":"latest_date"}},"table:uncategorized:L:TS:[object Object]":{"type":"aggregation","aggregation":{"property":"L:TS","aggregator":{"operator":"percent_per_group","groupName":"Complete"}}}},"sort":[{"property":"|oXv","direction":"descending"}],"searchQuery":"","userTimeZone":"Asia/Shanghai"}}'